package com.onewelcome.core

import android.os.Build
import com.onegini.mobile.sdk.android.model.OneginiClientConfigModel
import com.onewelcome.showcaseapp.R
import javax.inject.Inject

class OneginiConfigModel @Inject constructor() : OneginiClientConfigModel {
  /* Config model generated by SDK Configurator version: v6.1.1 */
  override val appIdentifier = "ExampleApp"
  override val appPlatform = "android"
  override val redirectUri = "oneginiexample://loginsuccess"
  override val appVersion = "6.3.0"
  override val baseUrl = "https://mobile-security-proxy.in.test.onewelcome.net"
  override val resourceBaseUrl = "https://mobile-security-proxy.in.test.onewelcome.net/resources/"
  override val keyStoreHash = "f5aa1047dc7bf03954cec54a23d7956fbbbae5f3e6ce898c2255f7f95622b787"
  override val serverPublicKey = "E054C0611BEFF50169CA8534CCFE36D315CE13D5CE6833B6095E4453F13BC469"
  override val serverType = "access"
  override val serverVersion = "4198eab"
  override val certificatePinningKeyStore = R.raw.keystore
  override val deviceName = "${Build.BRAND} ${Build.MODEL}"

  override fun toString(): String {
    return "ConfigModel{" +
        "  appIdentifier='" + appIdentifier + "'" +
        ", appPlatform='" + appPlatform + "'" +
        ", redirectUri='" + redirectUri + "'" +
        ", appVersion='" + appVersion + "'" +
        ", baseUrl='" + baseUrl + "'" +
        ", resourceBaseUrl='" + resourceBaseUrl + "'" +
        ", keyStoreHash='" + keyStoreHash + "'" +
        ", serverPublicKey='" + serverPublicKey + "'" +
        ", serverType='" + serverType + "'" +
        ", serverVersion='" + serverVersion + "'" +
        "}"
  }
}