package com.onewelcome.core

import android.os.Build
import com.onegini.mobile.sdk.android.model.OneginiClientConfigModel
import javax.inject.Inject

class OneginiConfigModel @Inject constructor() : OneginiClientConfigModel {
  /* Config model generated by SDK Configurator version: v6.1.1 */
  override val appIdentifier = "ExampleApp"
  override val appPlatform = "android"
  override val redirectUri = "oneginiexample://loginsuccess"
  override val appVersion = "7.13.0"
  override val baseUrl = "https://mobile-security-proxy.in.prod.onewelcome.net"
  override val resourceBaseUrl = "https://mobile-security-proxy.in.prod.onewelcome.net/resources/"
  override val keyStoreHash = "41e61925d640c624f46e4a7897a785efac7cc4a017ded981133d143e038dd656"
  override val serverPublicKey: String? = null
  override val serverType = "access"
  override val serverVersion = "1.71.0"
  override val certificatePinningKeyStore = R.raw.keystore
  override val deviceName = "${Build.BRAND} ${Build.MODEL}"

  override fun toString(): String {
    return "ConfigModel{" +
        "  appIdentifier='" + appIdentifier + "'" +
        ", appPlatform='" + appPlatform + "'" +
        ", redirectUri='" + redirectUri + "'" +
        ", appVersion='" + appVersion + "'" +
        ", baseUrl='" + baseUrl + "'" +
        ", resourceBaseUrl='" + resourceBaseUrl + "'" +
        ", keyStoreHash='" + keyStoreHash + "'" +
        ", serverPublicKey='" + serverPublicKey + "'" +
        ", serverType='" + serverType + "'" +
        ", serverVersion='" + serverVersion + "'" +
        "}"
  }
}
